server:
  port: 443
  http2:
    enabled: true
  ssl:
    enabled: true
    certificate-private-key: keystore/private.key
    certificate: keystore/telebot-bundle.pem
#    key-store-type: PKCS12 # The format used for the keystore. It could be set to JKS in case it is a JKS file
#    key-store: classpath:keystore/telebot-03.p12 # The path to the keystore containing the certificate
#    key-store-password: 12345678 # The password used to generate the certificate
#    key-alias: telebot.lostfoundpaw.com # The alias mapped to the certificate

spring:
  application:
    name: telebot-mini

#telegrambot:
#  userName: Choo1bot
#  #botToken: 710277744:AAHze1GFOc7yTxPjCWXrckQ-azKA7bYTW0Y #
#  botToken: 5905838405:AAEN3TSJo_JxW3oaQ82pbbb2yPGx1lqOKKM # @LostFoundPetsBot
#  botToken: 5805197032:AAFQYR6YU1a1wpVjmRZoT644JbZ2NJ4u3k8 # NemoMiniBot
#  webHookPath: https://telebot.lostfoundpaw.com/
#  adminId: 12345
#
#eventservice:
#  period: 600000